// Generated by CoffeeScript 1.10.0
(function() {
  var Api, ClassifyPage, Profile, Project, SiteBackground, SiteHeader, StackOfPages, TopBar, User, dash, homePageTemplate, teamPageTemplate;

  Api = require('zooniverse/lib/api');

  TopBar = require('zooniverse/controllers/top-bar');

  SiteBackground = require('./site-background');

  SiteHeader = require('./site-header');

  StackOfPages = require('stack-of-pages');

  homePageTemplate = require('./templates/home-page');

  dash = require('./lib/dash');

  ClassifyPage = require('./classify-page');

  Profile = require('zooniverse/controllers/profile');

  teamPageTemplate = require('./templates/team-page');

  User = require('zooniverse/models/user');

  Project = (function() {
    Project.prototype.parent = document.body;

    Project.prototype.background = '';

    Project.prototype.id = '';

    Project.prototype.producer = '';

    Project.prototype.title = '';

    Project.prototype.summary = '';

    Project.prototype.description = '';

    Project.prototype.about = '';

    Project.prototype.pages = null;

    Project.prototype.workflows = null;

    Project.prototype.tasks = null;

    Project.prototype.firstTask = '';

    Project.prototype.subjectGroup = false;

    Project.prototype.organizations = null;

    Project.prototype.scientists = null;

    Project.prototype.developers = null;

    function Project(configuration) {
      var content, firstTask, i, j, key, label, len, len1, page, property, ref, ref1, ref2, ref3, subjectGroup, tasks, title, value;
      if (configuration == null) {
        configuration = {};
      }
      for (property in configuration) {
        value = configuration[property];
        this[property] = value;
      }
      if (this.background) {
        this.siteBackground = new SiteBackground({
          src: this.background
        });
        this.siteBackground.el.appendTo(document.body);
      }
      if (this.id) {
        this.connect(this.id);
      }
      this.header = new SiteHeader({
        template: SiteHeader.prototype.template(this)
      });
      this.stack = new StackOfPages;
      this.stack.el.className += ' readymade-main-stack';
      if (this.summary || this.description) {
        this.addPage('#/', 'Home', homePageTemplate(this));
      }
      this.classifyPages = [];
      if (this.workflows != null) {
        ref = this.workflows;
        for (i = 0, len = ref.length; i < len; i++) {
          ref1 = ref[i], key = ref1.key, label = ref1.label, subjectGroup = ref1.subjectGroup, tasks = ref1.tasks, firstTask = ref1.firstTask;
          if (label == null) {
            label = 'Classify';
          }
          if (key == null) {
            key = dash(label).replace(/\-/g, '_');
          }
          page = new ClassifyPage({
            subjectGroup: subjectGroup != null ? subjectGroup : this.subjectGroup,
            workflow: key,
            tasks: tasks,
            firstTask: firstTask
          });
          this.addPage("#/" + (dash(label)), label, page);
          this.classifyPages.push(page);
        }
      } else if (this.tasks != null) {
        page = new ClassifyPage({
          tasks: this.tasks,
          firstTask: this.firstTask,
          subjectGroup: this.subjectGroup
        });
        this.addPage('#/classify', 'Classify', page);
        this.classifyPages.push(page);
      }
      if (this.profile !== false) {
        this.profile = new Profile;
        this.addPage('#/profile', 'Profile', this.profile);
      }
      if (this.pages != null) {
        ref2 = this.pages;
        for (j = 0, len1 = ref2.length; j < len1; j++) {
          page = ref2[j];
          for (title in page) {
            content = page[title];
            this.addPage("#/" + (dash(title)), title, "<div class='readymade-generic-page' data-readymade-page='" + (dash(title)) + "'>" + content + "</div>");
          }
        }
      }
      if (this.organizations || this.scientists || this.developers) {
        this.addPage('#/team', 'Team', teamPageTemplate(this));
      }
      if (this.parent != null) {
        this.header.el.appendTo(this.parent);
      }
      if ((ref3 = this.parent) != null) {
        ref3.appendChild(this.stack.el);
      }
      this.stack.onHashChange();
      User.fetch();
    }

    Project.prototype.connect = function(project) {
      this.api = new Api({
        project: project
      });
      this.topBar = new TopBar;
      return this.topBar.el.appendTo(document.body);
    };

    Project.prototype.addPage = function(href, label, content) {
      this.stack.add(href, content);
      return this.header.addNavLink(href, label);
    };

    return Project;

  })();

  module.exports = Project;

}).call(this);
