// Generated by CoffeeScript 1.10.0
(function() {
  var dash;

  dash = require('../lib/dash');

  module.exports = function(context) {
    var template;
    template = function() {
      var label, ref, workflows;
      workflows = (ref = this.workflows) != null ? ref : [
        {
          label: 'Classify'
        }
      ];
      return "<div class='readymade-home-page'> " + (this.summary ? "<div class='readymade-project-summary'> " + this.summary + " </div>" : '') + " " + (this.description ? "<div class='readymade-project-description'> " + this.description + " </div>" : '') + " <div class='readymade-footer'> " + (((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = workflows.length; i < len; i++) {
          label = workflows[i].label;
          results.push("<a href='#/" + (dash(label)) + "' class='readymade-call-to-action'> " + label + " </a>");
        }
        return results;
      })()).join('\n')) + " </div> </div>";
    };
    return template.call(context);
  };

}).call(this);
